### ISSUE TITLE
Use eprocessingnetwork along side Omnipay

### ISSUE THREAD

**Issue by jbowm2** [reinetwork/eprocessingnetwork#17]
trying to use this package alongside Omnipay, continue to fight errors for classes not found. I cannot find much documentation on using this package and could use some guidance.

**Comment by travisamiller** [comment]
Hi @jbowm2 this is just a driver that fits into Omnipay API.

You might want to try taking a look at the functional tests for some examples:

https://github.com/reinetwork/eprocessingnetwork/blob/master/tests/Functional/AuthorizeAndCapture.php

**Comment by jbowm2** [comment]
@travisamiller 

does this package need to be included inside the Omnipay vendor directory in the laravel app file tree?

**Comment by travisamiller** [comment]
No, it doesn't, but since we pretty much use this only internally we haven't actually registered with with Packagist so you have to provide the git repo details in your composer.json:

```
{
    "name": "something/something",
    "description": "something.com website",
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/reinetwork/eprocessingnetwork.git"
        }
    ],
    "require": {
        "reinetwork/eprocessingnetwork": "~1.0"
    }
}
```

**Comment by jbowm2** [comment]
@travisamiller 

Thanks for the assistance
